### ISSUE TITLE
Help creating the UI

### ISSUE THREAD

**Issue by EmporiumDevelopment** [ohYanoox/DialogueUIAPI#1]
Im trying to make a Tutorial for my server which uses your dialogue UI's, the actual code works when i use sendMessage. But when i try using dialogues nothing happens no errors in console, but nothing runs.

Im using this:

```
$skin = $player->getSkin();
                $skinId = $skin->getSkinId();
                $skinData = $skin->getSkinData();
                $capeData = $skin->getCapeData();
                $geometryName = $skin->getGeometryName();
                $geometryData = $skin->getGeometryData();

                $dialogue = DialogueAPI::create("Welcome", "Tour Guide", 0, "Hello" . $player->getName() . "Welcome to Emporium Prison! You are in the training area, this area will teach you about how things work in Emporium Prison. To get started get your pickaxe from the Tour Guide he can be found at the bottom of the stairs",
                    [DialogueButton::create("Next")]);
                $entity = new Human((new Location(0, 0, 0, EmporiumCore::getInstance()->getServer()->getWorldManager()->getWorldByName("TutorialMine"), 0, 0)), new Skin($skinId, $skinData, $capeData, $geometryName, $geometryData), null);
                $dialogue->displayTo([$player], $entity);
```

**Comment by ohYanoox** [comment]
Hello, thank you for reporting this problem.

I just found the incident: When the NpcDialoguePacket is sent to the client, the client does not seem to respond by displaying the requested interface, it displays the screen when a second same packet is sent. So your code does not allow the packet to be resent. I am fixing (hack method) this and adding a way to send the interface without the presence of an entity.

Can you try this to confirm what I suspect ?
Put this in onEnable() and interacts with any entity:
`
  DialogueAPI::register($this);
        Server::getInstance()->getPluginManager()->registerEvent(PlayerEntityInteractEvent::class, function(PlayerEntityInteractEvent $event)
        {
            $player = $event->getPlayer();
            $dialogue = DialogueAPI::create(
                "Welcome", "Tour Guide", 0, "Hello" . $player->getName() . "Welcome to Emporium Prison! You are in the training area, this area will teach you about how things work in Emporium Prison. To get started get your pickaxe from the Tour Guide he can be found at the bottom of the stairs",
                [DialogueButton::create("Next")
                ->setHandler(function(Player $player, string $buttonName): void {
                    $player->sendMessage("Test");
                })]);
            $dialogue->displayTo([$player], $event->getEntity());
        }, EventPriority::LOWEST,
            $this);
`

**Comment by ohYanoox** [comment]
Hello, thank you for reporting this problem.

I just found the incident: When the NpcDialoguePacket is sent to the client, the client does not seem to respond by displaying the requested interface, it displays the screen when a second same packet is sent. So your code does not allow the packet to be resent. I am fixing (hack method) this and adding a way to send the interface without the presence of an entity.

Can you try this to confirm what I suspect ?
Put this in onEnable() and interacts with any entity:
```PHP
  DialogueAPI::register($this);
        Server::getInstance()->getPluginManager()->registerEvent(PlayerEntityInteractEvent::class, function(PlayerEntityInteractEvent $event)
        {
            $player = $event->getPlayer();
            $dialogue = DialogueAPI::create(
                "Welcome", "Tour Guide", 0, "Hello" . $player->getName() . "Welcome to Emporium Prison! You are in the training area, this area will teach you about how things work in Emporium Prison. To get started get your pickaxe from the Tour Guide he can be found at the bottom of the stairs",
                [DialogueButton::create("Next")
                ->setHandler(function(Player $player, string $buttonName): void {
                    $player->sendMessage("Test");
                })]);
            $dialogue->displayTo([$player], $event->getEntity());
        }, EventPriority::LOWEST,
            $this);
```

**Comment by ohYanoox** [comment]
Hello, thank you for reporting this problem.

I just found the incident: When the NpcDialoguePacket is sent to the client, the client does not seem to respond by displaying the requested interface, it displays the screen when a second same packet is sent. So your code does not allow the packet to be resent. I am fixing (hacky method) this and adding a way to send the interface without the presence of an entity.

Can you try this to confirm what I suspect ?
Put this in onEnable() and interacts with any entity:
```PHP
  DialogueAPI::register($this);
        Server::getInstance()->getPluginManager()->registerEvent(PlayerEntityInteractEvent::class, function(PlayerEntityInteractEvent $event)
        {
            $player = $event->getPlayer();
            $dialogue = DialogueAPI::create(
                "Welcome", "Tour Guide", 0, "Hello" . $player->getName() . "Welcome to Emporium Prison! You are in the training area, this area will teach you about how things work in Emporium Prison. To get started get your pickaxe from the Tour Guide he can be found at the bottom of the stairs",
                [DialogueButton::create("Next")
                ->setHandler(function(Player $player, string $buttonName): void {
                    $player->sendMessage("Test");
                })]);
            $dialogue->displayTo([$player], $event->getEntity());
        }, EventPriority::LOWEST,
            $this);
```

**Comment by ohYanoox** [comment]
=> [https://github.com/pmmp/PocketMine-MP/blob/4562cfb85bc5f8d9bd15077716eb9956e784c975/src/entity/Entity.php#L1497](url)

I assume there's a delay between sending AddActorPacket (to spawn the entity to the client) and sending NpcDialoguePacket to display the dialog interface to the client.

However, I am adding a way to display a dialog interface without entity.

I close the ticket.

**Comment by EmporiumDevelopment** [comment]
Thank you it works ill let you know if i find any bugs
