### ISSUE TITLE
Bug with new release

### ISSUE THREAD

**Issue by EmporiumDevelopment** [ohYanoox/DialogueUIAPI#2]
If i press escape instead of clicking a button it leaves a floating villager

![image](https://user-images.githubusercontent.com/89197165/224447018-e0901ee3-17ed-47d4-906a-3fef399f569c.png)

**Comment by ohYanoox** [comment]
Indeed, I forgot to remove the fake entity when closing the interface. The fix version has been push. Thank you

**Comment by ohYanoox** [comment]
I have a bad fix, wait for a new answer from me

**Comment by ohYanoox** [comment]
fixed [https://github.com/ohYanoox/DialogueUIAPI/commit/e79f9ea54c863a3a9265eee95851af90e8f3e11e](url)

**Comment by EmporiumDevelopment** [comment]
it works thank you
