### ISSUE TITLE
Bug when using Button

### ISSUE THREAD

**Issue by GamilinoMC** [ohYanoox/DialogueUIAPI#3]
Hello, I´ve tried to use your DialogueAPI, but whenever I click a Button nothing happens and I stay in the menu and cant do anything to close it

This is my code:

public function onCommand(CommandSender $sender, Command $cmd, string $label, array $args): bool
    {
        $dialogue = DialogueAPI::create("Tools-Dialogue", "blacksmith", "Welcome to my little forge, do you want to §abuy §ror §csell §rsomething?",
            [
                DialogueButton::create("§aBuy")
                    ->setHandler(function (Player $player, string $buttonName): void
                    {
                        $this->ToolsUI($player);
                    }),
                DialogueButton::create("§cSell")
                    ->setHandler(function (Player $player, string $buttonName): void
                    {
                        $player->sendMessage("§cThis feature is comming soon...");
                    })]);

        if ($cmd->getName() === "shop") { 
            if($sender instanceof Player){
                $this->ShopUI($sender);
            }
        return true;    
        }
        if ( $cmd->getName() === "tools") {
            if($sender instanceof Player){
                $dialogue->displayTo([$sender]);
            }
        }
    return true;
    }

**Comment by ohYanoox** [comment]
I will deal with your problem later. I'll let you know. Thanks

**Comment by ohYanoox** [comment]
Read the doc. The first thing to do is to register my api in your Main => onEnable() :

```PHP
DialogueAPI::register($this);
```
